kind: ConfigMap
apiVersion: v1
metadata:
  name: fluentd-config
  namespace: devops-tongchen
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
data:
  system.conf: |-
    <system>
      root_dir /tmp/fluentd-buffers/
    </system>
  containers.input.conf: |-
    <source>
      @id fluentd-containers.log
      @type tail
      path /var/log/containers/*_devops-python_*.log,/var/log/containers/*_devops-node_*.log
      pos_file /var/log/devops.log.pos
      tag kubernetes.*
      read_from_head true
      <parse>
        @log_level debug
        @type multi_format
        <pattern>
          format json
          time_key timestamp
        </pattern>
      </parse>
    </source>
    # Detect exceptions in the log output and forward them as one log entry.
    <filter kubernetes.**>
      @type parser
      key_name log
      reserve_data true
      remove_key_name_field true
      <parse>
        @type multi_format
        <pattern>
          format json
        </pattern>
      </parse>
    </filter>
    <filter kubernetes.**>
      @id filter_kubernetes_metadata
      @type kubernetes_metadata
    </filter>
    <filter kubernetes.**>
      @type record_transformer
      enable_ruby
      <record>
        k8s ${record["kubernetes"]}
      </record>
      remove_keys $.kubernetes,$.k8s.pod_id,$.k8s.container_image_id,$.k8s.master_url,$.k8s.namespace_id,$.k8s.labels.pod-template-hash
    </filter>
  output.conf: |-
    <match **>
      @type elasticsearch
      @log_level debug
      host "xxx.cloud.es.io"
      user elastic
      password "xxxxx"
      scheme https
      logstash_format true
      port 9243
      <buffer>
        timekey 60s
        flush_mode interval
        flush_interval 10
      </buffer>
    </match>
