apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: generate-build-id
  namespace: tekton-pipelines
spec:
  results:
    - name: timestamp
      description: Current timestamp
    - name: build-id
      description: ID of the current build
  steps:
    - name: get-timestamp
      image: zshusers/zsh:4.3.15
      script: |
        #!/usr/bin/env bash
        ts=`date "+%Y%m%d-%H%M%S" -d "+8 hours"`
        echo "Current Timestamp: ${ts}"
        echo ${ts} | tr -d "\n" | tee $(results.timestamp.path)
    - name: get-buildid
      image: zshusers/zsh:4.3.15
      script: |
        #!/usr/bin/env bash
        ts=`cat $(results.timestamp.path)`
        buildId=${ts}
        echo ${buildId} | tr -d "\n" | tee $(results.build-id.path)
