apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: collect-report
  namespace: tekton-pipelines
  labels:
    app.kubernetes.io/version: "0.1"
spec:
  workspaces:
    - name: reportdir
    - name: nginxdir
  params:
    - name: SUBPATH
      type: string
      default: "./reports"
    - name: PROJECT
      type: string
  steps:
    - name: collect-report
      image: busybox
      script: |
        #!/bin/sh 
        [[ ! -d $(workspaces.nginxdir.path)/$(params.PROJECT) ]] && mkdir $(workspaces.nginxdir.path)/$(params.PROJECT)
        rm -fr $(workspaces.nginxdir.path)/$(params.PROJECT)/*
        cp -r $(params.SUBPATH)/* $(workspaces.nginxdir.path)/$(params.PROJECT)
      workingDir: $(workspaces.reportdir.path)/
