---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: from-git-get-image-tag
  namespace: tekton-pipelines
spec:
  results:
  - name: image_url
  - name: image_tag
  params:
    - name: git_iaas_url
      default: gitlab.devops.soulchild.cn/root/devops-iaas.git
    - name: tool-image
      default: bitnami/git:2.35.1
      description: task run image
    - name: projectname
  steps:
    - name: get-image-tag
      image: $(params.tool-image)
      env:
        - name: GIT_USERNAME
          valueFrom:
            secretKeyRef:
              name: gitlab-auth
              key: username
              optional: true
        - name: GIT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gitlab-auth
              key: password
              optional: true
      script: |-
        #!/bin/bash
        git clone --branch $(params.projectname) --depth 1 http://${GIT_USERNAME}:${GIT_PASSWORD}@$(params.git_iaas_url) iaas
        cd iaas/prod/$(params.projectname)
        image_url=$(grep 'image:' deploy.yaml| awk '{print $2}' | sed s#-prod##) 
        printf "%s" $image_url | tee $(results.image_url.path)
        image_tag=$(grep 'image:' deploy.yaml| awk -F: '{print $NF}' | sed s#-prod##)
        printf "%s" $image_tag | tee $(results.image_tag.path)
