apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-merge
  namespace: tekton-pipelines
  labels:
    app.kubernetes.io/version: "0.1"
spec:
  params:
  - name: projectname
  - name: tagname
    default: ""
  - name: branchfrom
    default: release
  - name: branchto
    default: master
  - name: deletesource
    default: "false"
  steps:
    - name: git-merge
      image: harbor.devops.soulchild.cn/devops/gitlab:v1
      env:
      - name: BRANCH_FROM
        value: $(params.branchfrom)
      - name: BRANCH_TO
        value: $(params.branchto)
      - name: PROJECT_NAME
        value: $(params.projectname)
      - name: TAG_NAME
        value: $(params.tagname)
      - name: DELETE_SOURCE
        value: $(params.deletesource)
      command: ["python", "/merge.py"]
