apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: integration-test
  namespace: tekton-pipelines
  labels:
    app.kubernetes.io/version: "0.1"
spec:
  workspaces:
  - name: report-dir
  params:
  - name: projectname
  results:
  - name: test-result
  steps:
    - name: interface-test
      image: ibmcom/curl:4.0.0
      workingDir: $(workspaces.report-dir.path)
      script: |
        #!/bin/bash
        mkdir reports -p
        echo "haha ok" > reports/integrationtestReport.html
        grep 'ok' reports/integrationtestReport.html || exit 1
        echo yes | tr -d "\n" | tee $(results.test-result.path)
