---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: notification
  namespace: tekton-pipelines
spec:
  params:
    - name: tool-image
      default: ibmcom/curl:4.0.0
    - name: content
  steps:
    - name: notification
      image: $(params.tool-image)
      script: |-
        #!/bin/bash
        curl -s 'https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=xxxxxxxxxxxx' -H 'Content-Type: application/json'  -d "{\"msgtype\": \"text\", \"text\": {\"content\": \"$(params.content)\"}}"
