apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: python-quality-gate
  namespace: tekton-pipelines
  labels:
    app.kubernetes.io/version: "0.1"
spec:
  workspaces:
    - name: source
  params:
    - name: IMAGE
      type: string
      default: harbor.devops.soulchild.cn/devops/python:ci
  steps:
    - name: quality-gate
      image: $(params.IMAGE)
      script: |-
        #!/bin/bash
        cat > package_checker.py <<EOF
        limit = {'Flask': (2, 0, 3)}
        def check():
            with open('requirements.txt', 'r') as f:
                for line in f.read().splitlines():
                    package, version = line.split('==')
                    version = tuple((int(_x) for _x in version.split('.')))
                    if limit.get(package) and limit[package] > version:
                        print(f'warning: {package} version should gather than {limit[package]};current {version}')
        if __name__ == '__main__':
            check()
        EOF
        python3 package_checker.py
      workingDir: $(workspaces.source.path)/
