
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: sonarqube-scanner
  namespace: tekton-pipelines
  labels:
    app.kubernetes.io/version: "0.1"
spec:
  workspaces:
    - name: source
  steps:
    - name: sonar-scan
      image: docker.io/sonarsource/sonar-scanner-cli
      workingDir: $(workspaces.source.path)
      command:
        - sonar-scanner
