apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: website-git
spec:
  type: git
  params:
  - name: url
    value: https://github.com/soulchildwm/tekton-demo.git
  - name: revision
    value: python-website
