apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: python-pipeline
spec:
  workspaces:
  - name: shared-code
  - name: pipcache
  description: python ci pipeline
  resources:
  - name: code
    type: git
  params:
  - name: directory
    description: 相对路径,工作目录
    type: string
  - name: base-version
  - name: image
    type: string
  - name: dockerfile
    type: string
  tasks:
  - name: py-test
    taskRef:
      name: py-test
    params:
    - name: directory
      value: $(params.directory)
    resources:
      inputs: 
      - name: code
        resource: code
    workspaces:
    - name: code
      workspace: shared-code
    - name: pipcache
      workspace: pipcache
  - name: gentrate-build-id
    taskRef: 
      name: generate-build-id
    runAfter:
    - py-test
    params:
    - name: base-version
      value: $(params.base-version) 
  - name: dind-build-push
    taskRef:
      name: dind-build-push
    runAfter:
    - py-test
    - gentrate-build-id
    params:
    - name: image
      value: $(params.image):$(tasks.gentrate-build-id.results.build-id)
    - name: dockerfile
      value: $(params.dockerfile)
    workspaces:
    - name: code
      workspace: shared-code
