apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: website-ci-run-
spec:
  workspaces:
  - name: pipcache
    PersistentVolumeClaim:
      claimName: pipcache
  - name: shared-code
    volumeClaimTemplate:
      spec:
        accessModes: 
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  pipelineRef:
    name: python-ci
  resources:
  - name: code
    resourceRef:
      name: website-git
  params:
  - name: directory
    value: app
  - name: base-version
    value: v1.0
  - name: image
    value: registry.cn-shanghai.aliyuncs.com/soulchild/zero
  - name: dockerfile
    value: "./Dockerfile"
  serviceAccountName: website-auth-sa
  timeout: 60m
