apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: python-pipeline
  namespace: tekton-pipelines
spec:
  serviceAccountName: tekton-triggers-devops
  triggers:
  - name: python
    bindings:
      - ref: gitlab-binding
    template:
      ref: python-template
    interceptors:
      - gitlab:
          secretRef:
            secretName: gitlab-webhook
            secretKey: key
          eventTypes:
            - Push Hook
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: el-python
  namespace: tekton-pipelines
  annotations:
    kubernetes.io/ingress.class: nginx
spec:       
  rules: 
  - host: el-python.devops.soulchild.cn
    http:
      paths:
      - backend:
          serviceName: el-python-pipeline
          servicePort: 8080
        path: /
