apiVersion: v1
kind: Secret
metadata:
  name: ssh-key
  namespace: tekton-pipelines
  annotations:
    tekton.dev/git-0: gitlab.devops.soulchild.cn
type: kubernetes.io/ssh-auth
stringData:
  ssh-privatekey: |-
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEAxKAzyTTx2W+4B6Ps51/vAbI5Y/z2wQ7RhcFFOG5MSC5ew8a4
    tYF4DFvj/Wbs/LFTk3lSrAlfVaoXQhWxdD4XAFEwo+TRkz5ZzEeT8y9mwL34v/1x
    WC7/A29sT9dCoUTy+wDzu/tr0PCTPKTnzaLqLEraLPEk3z5BVt+6P8hj/g7rXUE6
    drJiU9XBte6EjG7ehu5TGrCcYCbp80qVqVrtcBOqYIAltFMfNxA7CUvO66zgpx2Y
    JHDSEatountFvLZwpCj5hXNf0xpy3V7H9rQkac9gMfNSFEcUF6ZE3pg0GuSrBiGp
    tw8Rk286/RQXkqhT+iVziLq5+Pxsr4peaIR9EwIDAQABAoIBAQCZdWMVfTHofw4F
    QIYsCq6SB1RNWmgHQxZ5qt7obQUyLKafa6BLYLGeC7XD1ynNCmTtK3o/dM0oIakn
    VaD61V7ES5mHwJVksvwIuDCbUvqCIYJb7WUh6wPy3WqOYbXKAfMVvad8pnx+RNTV
    NusHjkfvq7fd7ZLWfVMnh1NoZnDMHeCOhOgZJntht8VOuKmFNyRqDlewycHav7T5
    DGKVmAsrhX6AqezMFHEiDtH/Z6wLWILkod6XP6rUba5d6I1ndG9xiwqLTnRKLZ3e
    niFSMwoilGRMm61MfLNhMNzprb6T4FAlwB5agU2rCvTshTCnq//A8ziFV/uJXoif
    kMXgiSNhAoGBAOL5+PTgAc66uR41Eg4xRx0yjx0Vh3HqiBYBjw8HzNzA1gaLY2rB
    23NqCrRx0HqNrWAn+gG9TWrvEYZY7QpndExbQC7CoVFqLJ/9UlqRIXnzWBYOsF3o
    lmt7cBkO/LGJzkI+YrgDsihlC9uQsIw6wO4XBz/XzXbX7SiN4BE1wsZxAoGBAN3E
    tQCGSRc/jAEmMOZ1VosstWh8Gh9mofepO8fOXIbqGykW4/8XCaaDWnrnabwa/RA1
    hZlZqJhb1J+zo0QjA51uOqXsLoaBn8K/eeG0ut6GyiNCTr2yEaVaPVuXQg9Ez+Yh
    OoqvVexMLgJ/mjfH5GXbftnQU1gxgCsr0DjciSXDAoGATXbg57oYA9UoXs3gBqX8
    zlM2EsgJPPC9Vz1a9NdFrMXHhd5GpOXans4/Lwx1CY6W8G1UXwmbhXZoNcDdzaI3
    R+QQyKS2Z9Hjvwq285/6m+NYWdbTjIlX5QDw5ix+Q51znpoqGQFx6WVrIZmFF6bp
    t5h2aeyd/AR/tUqOgXEms5ECgYAxcDKxpT4SEraRYwQvvCTI7fSbEF96dJTS80VC
    a7ywzuuzI0k8itQ57Lp0/7XQm2ui+2uHHje5j289Evzoqa2aoQIuDxLoJWmKLslr
    CbFG/mF9rsCDBXltlUpsarHtWXfHY8z7Mc9D2E/BetTUbpl6I46J3ClYVeCuvxuy
    MWfZpQKBgQDOwmNZ5ybCbp/3VfelFVBv5XNvYHDGvk3q5VGOkyVRmR9hYARqEDd3
    Fq3bpUPno/aE9aH3LIz9pnSOoZECfSvy63l6JvHGIKfVc3x72nOxF1kTbnHP/Efs
    QEIYO1o8Z//tTG8zzzvEWFTcKbEjUS7nuhHXddRPYSN5UhvDqHZU/w==
    -----END RSA PRIVATE KEY-----
  known_hosts: gitlab.devops.soulchild.cn ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDYdq+o3+egyLro5mFh2i1ZYgWBLfdpxmA7TGLIZtEmMhFAk2ssNk7Cn1ZMHYzuDhoK0vF1AMHwPW8FBpn2AmPcCL2kVOr/3HNxursUCB4sxGZPRk0UzgPJSxuWRN4GIpbfViLgK7Wvry5UuYKCq3+UKUzfC70DQuo/RZD36dQ+r3uVQ7ps3/Msq6u/UhJvl9IRWNefWJjYp+KNOuXnmoXwJR6KhCsseaq9n9MCGh0ykn1lijxTT6zp8wP0KBL7U16vwHehK4TZT1O/DTWisjYscUAdAWbugoaQ3IsrfYr16ow3Y592wu122dI1YJTPgJsxVljUTJuzeRFmJYJWYFlH
