apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pipcache
  namespace: tekton-pipelines
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: alicloud-disk-available
