apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cd-pipeline
  namespace: tekton-pipelines
spec:
  params:
  - name: project
    type: string
  tasks:
  - name: get-image-tag
    taskRef: 
      name: from-git-get-image-tag
    params:
    - name: projectname
      value: $(params.project)
  - name: generate-prod-image
    taskRef:
      name: skopeo-copy 
    params:
    - name: srcImageURL
      value: "$(tasks.get-image-tag.results.image_url)"
    - name: destImageURL
      value: "$(tasks.get-image-tag.results.image_url)-prod"
  - name: git-merge-iaas
    runAfter:
    - generate-prod-image
    taskRef:
      name: git-merge
    params:
    - name: projectname
      value: "devops-iaas"
    - name: branchfrom
      value: $(params.project)
  - name: notification
    runAfter:
    - git-merge-iaas
    taskRef:
      Name: notification
    params:
      - name: content
        value: "【Tekton - $(params.project)】\\n线上即将开始灰度发布\\n测试报告: http://reports.devops.soulchild.cn/$(params.project)"
  - name: argocd-deploy-pord
    runAfter: 
    - git-merge-iaas
    taskRef:
      name: argocd-task-sync-and-wait
    params:
    - name: application-name
      value: "$(params.project)"
  - name: git-merge-code
    when:
    - input: "$(tasks.argocd-deploy-pord.results.deploy-result)"
      operator: in
      values: ["yes"]
    runAfter:
    - argocd-deploy-pord
    taskRef:
      name: git-merge
    params:
    - name: projectname
      value: "$(params.project)"
    - name: tagname
      value: "$(tasks.get-image-tag.results.image_tag)"
