apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: gitlab-binding
  namespace: tekton-pipelines
spec:
  params:
  - name: gitrevision
    value: $(body.checkout_sha)
  - name: gitrepositoryurl
    value: $(body.project.ssh_url)
  - name: projectname
    value: $(body.repository.name)
  - name: commitcontent
    value: $(body.commits[1].message)
