apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: qyweixin-webhook
  namespace: devops-tongchen
spec:
  selector:
    matchLabels:
      app: qyweixin-webhook
  template:
    metadata:
      labels: 
        app: qyweixin-webhook
    spec:
      containers: 
      - name: qyweixin-webhook
        imagePullPolicy: Always
        ports:
        - name: web
          containerPort: 80
        resources:
          limits:
            cpu: 300m
            memory: 512Mi
        # The source code for this mirror is included in the python-devops project
        image: harbor.devops.soulchild.cn/devops/wxcallback
---
apiVersion: v1
kind: Service
metadata:
  name: qyweixin-webhook
  namespace: devops-tongchen
spec:       
  type: LoadBalancer
  ports: 
  - name: web 
    targetPort: 80
    port: 80
  selector:
    app: qyweixin-webhook
