apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reports-nginx
  namespace: tekton-pipelines
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: managed-nfs-storage
