apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: reports-nginx
  namespace: tekton-pipelines
spec:
  selector:
    matchLabels:
      app: reports-nginx
  template:
    metadata:
      labels: 
        app: reports-nginx
    spec:
      initContainers:
      - name: inti-config
        image: nginx:1.14.2
        volumeMounts:
        - name: config
          mountPath: /nginx-config
        command:
        - /bin/bash
        - -c
        args:
        - "sed '3a \ \ \ \ autoindex    on;' /etc/nginx/conf.d/default.conf > /nginx-config/default.conf"
      containers: 
      - name: nginx
        image: nginx:1.14.2
        ports:
        - name: web
          containerPort: 80
        volumeMounts:
        - name: reports-nginx
          mountPath: /usr/share/nginx/html/
        - name: config
          mountPath: /etc/nginx/conf.d/
      volumes:
      - name: reports-nginx
        persistentVolumeClaim:
          claimName: reports-nginx
      - name: config
        emptyDir: {}
        
---
apiVersion: v1
kind: Service
metadata:
  name: reports-nginx
  namespace: tekton-pipelines
spec:
  type: ClusterIP
  ports:
  - name: web
    targetPort: 80
    port: 80
  selector:
    app: reports-nginx
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: reports-nginx
  namespace: tekton-pipelines
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: reports.devops.soulchild.cn
    http:
      paths:
      - backend:
          serviceName: reports-nginx
          servicePort: 80
        path: /
