apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: cd-template
  namespace: tekton-pipelines
spec:
  params:
  - name: projectname
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: cd-pipeline-run-
    spec:
      serviceAccountName: tekton-auth
      pipelineRef:
        name: cd-pipeline
      params:
        - name: project
          value: $(tt.params.projectname)
