apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: docker-build-push
spec:
  volumes:
  - name: docker-socket
    hostPath:
      type: Socket
      path: /var/run/docker.sock
  params:
  - name: image
    description: 镜像名称
  - name: dockerfile
    description: Your Dockerfile Path
    default: $(workspaces.code.path)/Dockerfile
  - name: contextPath
    type: string
    description: Docker build context
    default: ./
  steps:
  - name: docker-build
    image: docker:stable
    workingDir: $(workspaces.code.path)
    command: ["docker"]
    args: ["build","-f","$(params.pathToDockerfile)","-t","$(params.imageName)","$(params.contextPath)"]
  - name: docker-push
    image: docker:stable
    args: ["push", "$(params.imageName)"]
    volumeMounts:
      - name: docker-socket
        mountPath: /var/run/docker.sock
  workspaces: 
  - name: code   
